version: "3"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: avn-tokens
      POSTGRES_PASSWORD: avn-tokens
    volumes:
      - ./db/data/${AVN_ENV}:/var/lib/postgresql/data
    ports:
      - "23800:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    networks:
      - tokens

  # PG Admin is optional.
  # pgadmin:
  #   container_name: pgadmin_container_2
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #      - ./db/data/pgadmin:/var/lib/pgadmin
  #   ports:
  #     - "5544:80"
  #   restart: unless-stopped
  #   networks:
  #     - tokens

networks: 
  tokens: