apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/inbound-cidrs: "0.0.0.0/0"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certificateArn }}
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
  labels:
    app: {{ .Chart.Name }}

spec:
  rules:
  {{- if .Values.archive.explorer.enabled }}
  {{- if .Values.archive.explorer.url }}
  - host: {{ .Values.archive.explorer.url }}
  {{- else }}
  - host: archive-explorer.{{ .Values.enviroment }}.aventus.io
  {{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.archive.explorer.name }}
            port:
              number: {{ .Values.archive.explorer.service.www.port }}
  {{- end }}

  {{- if .Values.archive.gateway.enabled }}
  {{- if .Values.archive.gateway.url }}
  - host: {{ .Values.archive.gateway.url }}
  {{- else }}
  - host: archive-gateway.{{ .Values.enviroment }}.aventus.io
  {{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.archive.gateway.name }}
            port:
              number: {{ .Values.archive.gateway.service.www.port }}
  {{- end }}

  {{- if .Values.balances.server.enabled }}
  {{- if .Values.balances.server.url }}
  - host: {{ .Values.balances.server.url }}
  {{- else }}
  - host: balances-explorer.{{ .Values.enviroment }}.aventus.io
  {{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.balances.server.name }}
            port:
              number: {{ .Values.balances.server.service.www.port }}
  {{- end }}
  
  {{- if .Values.fees.server.enabled }}
  {{- if .Values.fees.server.url }}
  - host: {{ .Values.fees.server.url }}
  {{- else }}
  - host: fees-explorer.{{ .Values.enviroment }}.aventus.io
  {{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.fees.server.name }}
            port:
              number: {{ .Values.fees.server.service.www.port }}
  {{- end }}

  {{- if .Values.staking.server.enabled }}
  {{- if .Values.staking.server.url }}
  - host: {{ .Values.staking.server.url }}
  {{- else }}
  - host: staking-explorer.{{ .Values.enviroment }}.aventus.io
  {{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.staking.server.name }}
            port:
              number: {{ .Values.staking.server.service.www.port }}
  {{- end }}

  {{- if .Values.summary.server.enabled }}
  {{- if .Values.summary.server.url }}
  - host: {{ .Values.summary.server.url }}
  {{- else }}
  - host: summary-explorer.{{ .Values.enviroment }}.aventus.io
  {{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.summary.server.name }}
            port:
              number: {{ .Values.summary.server.service.www.port }}
  {{- end }}
  
  {{- if .Values.tokens.server.enabled }}
  {{- if .Values.tokens.server.url }}
  - host: {{ .Values.tokens.server.url }}
  {{- else }}
  - host: tokens-explorer.{{ .Values.enviroment }}.aventus.io
  {{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.tokens.server.name }}
            port:
              number: {{ .Values.tokens.server.service.www.port }}
  {{- end }}
