{{- if .Values.fees.processor.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.fees.processor.name }}-config
data:
  AVN_ENV: {{ .Values.avn_env }}
  ARCHIVE_URL: https://archive-gateway.{{ .Values.enviroment }}.aventus.io/graphql 
  PROCESSOR_PROMETHEUS_PORT: "3000"
  PROCESSOR_BATCH_SIZE: "50"
  #PROCESSOR_RANGE_FROM: "0"
  #PROCESSOR_RANGE_TO: "0"
{{- end }}
