services:
  db:
    image: postgres:14  # CockroachDB cluster might be a better fit for production deployment
    restart: always
    volumes:
      - ./db/data/testnet:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avn-archive-testnet
    networks:
      - testnet

  ingest:
    depends_on:
      - db
    restart: on-failure
    image: subsquid/substrate-ingest:firesquid
    command: [
        # testnet:
        "-e", "wss://avn.test.aventus.io",
        # add another endpoint to increase archiving speed and reliability.
        # "-e", "wss://avn.test-2.aventus.io",
        "-c", "10", # allow up to 10 pending requests for the above endpoint (default is 5)

        # "--start-block", "100000", # uncomment to specify a non-zero start block

        "--out", "postgres://postgres:postgres@db:5432/avn-archive-testnet",

        # types for solochain
        "--types-bundle", "/app/avn-types.json"
    ]
    volumes:
      - ./avn-types.json/:/app/avn-types.json
    networks:
      - testnet

  gateway:
    depends_on:
      - db
    image: subsquid/substrate-gateway:firesquid
    environment:
      DATABASE_MAX_CONNECTIONS: 5
      RUST_LOG: "actix_web=info,actix_server=info"
    command: [
       "--database-url", "postgres://postgres:postgres@db:5432/avn-archive-testnet",
       # "--evm-support" # uncomment for chains with Frontier EVM pallet
                         # (e.g. Moonbeam/Moonriver or Astar/Shiden)
    ]
    ports:
      - "8888:8000"
    networks:
      - testnet

  # Explorer service is optional.
  # It provides rich GraphQL API for querying archived data.
  # Many developers find it very useful for exploration and debugging.
  explorer:
    image: subsquid/substrate-explorer:firesquid
    environment:
      DB_TYPE: postgres # set to `cockroach` for Cockroach DB
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: "avn-archive-testnet"
      DB_USER: "postgres"
      DB_PASS: "postgres"
      # setup sensible limits for production
      # GQL_DB_STATEMENT_TIMEOUT_MS: 2000
      # GQL_MAX_ROOT_FIELDS: 200
      # GQL_MAX_RESPONSE_NODES: 300000
    ports:
      - "4444:3000"
    networks:
      - testnet

  # PG Admin is optional.
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./db/pg-admin:/var/lib/pgadmin
    ports:
      - "5543:80"
    networks:
      - testnet
    restart: unless-stopped

networks:
  testnet: