{{- if or .Values.tokens.server.enabled .Values.tokens.processor.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tokens-spc
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters: 
    objects: |
      - objectName: {{ .Values.tokens.secretsManagerName }}
        objectType: "secretsmanager"
        jmesPath:
          - path: db_username
            objectAlias: dbusername
          - path: db_password
            objectAlias: dbpassword
          - path: db_hostname
            objectAlias: dbhostname
          - path: db_port
            objectAlias: dbport
          - path: db_name
            objectAlias: dbname
  secretObjects:                
    - secretName: tokens-secrets
      type: Opaque
      data:
        - objectName: dbusername
          key: db_username
        - objectName: dbpassword
          key: db_password
        - objectName: dbhostname
          key: db_hostname
        - objectName: dbport
          key: db_port
        - objectName: dbname
          key: db_name
{{- end }}
