{{- if .Values.fees.processor.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fees.processor.name }}
  labels:
    app: {{ .Values.fees.processor.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.fees.processor.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.fees.processor.name }}
        appVersion: {{ .Chart.AppVersion }}
        helmVersion: {{ .Chart.Version }}
    spec:
      serviceAccountName: {{ .Values.fees.serviceAccount.name }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: fees-spc
      containers:
        - name: {{ .Values.fees.processor.name }}
          image: "{{ .Values.fees.image.repository }}:{{ .Values.fees.image.tag }}"
          imagePullPolicy: {{ .Values.fees.image.pullPolicy }}
          command: ['yarn', 'processor:start']
          livenessProbe:
            httpGet:
              path: /metrics
              port: 3000
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: 3000
            timeoutSeconds: 5
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Values.fees.processor.name }}-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: fees-secrets
                  key: db_username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: fees-secrets
                  key: db_password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: fees-secrets
                  key: db_hostname
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: fees-secrets
                  key: db_port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: fees-secrets
                  key: db_name
{{- end }}
