{{- if .Values.staking.processor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.staking.processor.name }}
  labels:
    app: {{ .Values.staking.processor.name }}
    helmVersion: {{ .Chart.Version }}
spec:
  type: {{ .Values.staking.processor.service.www.type }}
  ports:
  - name: {{ .Values.staking.processor.name }}
    port: {{ .Values.staking.processor.service.www.port }}
    targetPort: {{ .Values.staking.processor.service.www.port }}
    protocol: TCP
  selector:
    app: {{ .Values.staking.processor.name }}
{{- end }}
