{{- if .Values.archive.ingest.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.archive.ingest.name }}
  labels:
    app: {{ .Values.archive.ingest.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.archive.ingest.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.archive.ingest.name }}
        appVersion: {{ .Chart.AppVersion }}
        helmVersion: {{ .Chart.Version }}
    spec:
      serviceAccountName: {{ .Values.archive.serviceAccount.name }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: archive-spc
      containers:
        - name: {{ .Values.archive.ingest.name }}
          image: "{{ .Values.archive.ingest.image.repository }}:{{ .Values.archive.ingest.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.archive.ingest.image.pullPolicy }}
          args: ['-e', '$(AVN_NODE)', '-c', '10', '--out', 'postgres://$(DB_USER):$(DB_PASS)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)']
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9090
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9090
            timeoutSeconds: 5
          env:
            - name: AVN_NODE
              valueFrom:
                secretKeyRef:
                  name: archive-secrets
                  key: avn_node
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: archive-secrets
                  key: db_username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: archive-secrets
                  key: db_password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: archive-secrets
                  key: db_hostname
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: archive-secrets
                  key: db_port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: archive-secrets
                  key: db_name
{{- end }}
