{{- if or .Values.archive.gateway.enabled .Values.archive.explorer.enabled .Values.archive.ingest.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: archive-spc
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters: 
    objects: |
      - objectName: {{ .Values.archive.secretsManagerName }}
        objectType: "secretsmanager"
        jmesPath:
          - path: avn_node
            objectAlias: avnnode
          - path: db_username
            objectAlias: dbusername
          - path: db_password
            objectAlias: dbpassword
          - path: db_hostname
            objectAlias: dbhostname
          - path: db_port
            objectAlias: dbport
          - path: db_name
            objectAlias: dbname
          - path: db_type
            objectAlias: dbtype
  secretObjects:                
    - secretName: archive-secrets
      type: Opaque
      data:
        - objectName: avnnode
          key: avn_node
        - objectName: dbusername
          key: db_username
        - objectName: dbpassword
          key: db_password
        - objectName: dbhostname
          key: db_hostname
        - objectName: dbport
          key: db_port
        - objectName: dbname
          key: db_name
        - objectName: dbtype
          key: db_type
{{- end }}
