name: Check Balances app Eslint

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/balances/**'

defaults:
  run:
    working-directory: apps/balances

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Run Eslint checks
        run: yarn eslint:check
