name: Build Balances

on:
  push:
    branches:
      - ew-main
jobs:
  ew-docker-build:
    name: EW Explorer Balances
    uses: ./.github/workflows/docker-build.yml
    with:
      runner: avn-runner
      config_creds: false
      short_image_name: balances
      ecr_repository_prefix: explorer
      aws_region: us-east-1
      aws_account_id: 541507968610
      dockerfile: apps/balances/Dockerfile
