name: Build Fees

on:
  push:
    branches:
      - ew-main

jobs:
  ew-docker-build:
    name: EW Explorer Fees
    uses: ./.github/workflows/docker-build.yml
    with:
      runner: avn-runner
      config_creds: false
      short_image_name: fees
      ecr_repository_prefix: explorer
      aws_region: us-east-1
      aws_account_id: 541507968610
      dockerfile: apps/fees/Dockerfile
