name: Build Fees

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - 'apps/fees/**'
      - 'packages/types/**'
      - 'packages/config/**'
      - 'packages/utils/**'
  push:
    branches:
      - main
    paths:
      - 'apps/fees/**'
      - 'packages/types/**'
      - 'packages/config/**'
      - 'packages/utils/**'

jobs:
  avn-docker-build:
    name: AvN Explorer Fees
    uses: ./.github/workflows/docker-build.yml
    with:
      runner: gh-ubuntu-2404-x64
      short_image_name: fees
      ecr_repository_prefix: explorer
      aws_region: eu-west-1
      aws_account_id: 931945598683
      dockerfile: apps/fees/Dockerfile

  ew-docker-build:
    name: EW Explorer Fees
    if: ${{ github.event_name == 'workflow_dispatch' && github.ref_name == 'main' }}
    uses: ./.github/workflows/docker-build.yml
    with:
      runner: gh-ubuntu-2404-x64
      config_creds: false
      short_image_name: fees
      ecr_repository_prefix: explorer
      aws_region: us-east-1
      aws_account_id: 541507968610
      dockerfile: apps/fees/Dockerfile
