name: Build Fees

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - 'apps/fees/**'
  push:
    branches:
      - main
    paths:
      - 'apps/fees/**'

jobs:
  build:
    name: AvN Explorer Fees
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      short_image_name: fees
      ecr_repository_prefix: avn-explorer
      aws_region: eu-west-2
      dockerfile: apps/fees/Dockerfile
