name: Build Staking

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - 'apps/staking/**'
  push:
    branches:
      - main
    paths:
      - 'apps/staking/**'

jobs:
  build:
    name: AvN Explorer Staking
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      short_image_name: staking
      ecr_repository_prefix: avn-explorer
      aws_region: eu-west-2
      dockerfile: apps/staking/Dockerfile
