name: Build Tokens

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - 'apps/tokens/**'
  push:
    branches:
      - main
    paths:
      - 'apps/tokens/**'

jobs:
  build:
    name: AvN Explorer Tokens
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      short_image_name: tokens
      ecr_repository_prefix: avn-explorer
      aws_region: eu-west-2
      dockerfile: apps/tokens/Dockerfile
