name: Check Tokens app

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/tokens/**'
      # check if one of the used packages is changed
      - 'packages/types/**'
      - 'packages/config/**'
      - 'packages/utils/**'

jobs:
  check_search_app:
    name: Check Tokens App
    uses: Aventus-Network-Services/shared-workflows/.github/workflows/check-yarn-application.yml@v5.12.0
    with:
      working_directory: apps/tokens
      build_command: |
        yarn workspace @avn/types run build
        yarn workspace @avn/config run build
        yarn workspace @avn/utils run build
