name: Check Types package

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/types/**'

jobs:
  check_types_package:
    name: Check Types Package
    uses: Aventus-Network-Services/shared-workflows/.github/workflows/check-yarn-application.yml@v5.12.0
    with:
      working_directory: packages/types
      build_packages: false
