name: Check Utils package

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/utils/**'

defaults:
  run:
    working-directory: packages/utils

jobs:
  check_utils_package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.6'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
        run: yarn workspaces @avn/types run build
      - name: Build utils package
        run: yarn workspaces @avn/config run build
      - name: Build utils package
      - name: Run Typescript checks
        run: yarn types:check
