name: Check Types package

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, edited]
    branches: [main]
    paths:
      - 'packages/types/**'

jobs:
  check:
    name: Check Types Package
    uses: AventusDAO/shared-workflows/.github/workflows/check-yarn-application.yml@v5.20.0
    with:
      checkout_repository: ${{github.event.pull_request.head.repo.full_name}}
      checkout_ref: ${{github.event.pull_request.head.ref}}
      working_directory: packages/types
      build_packages: false
