name: Check Node Manager app

on:
  pull_request_target:
    branches: [main]
    paths:
      - 'apps/node-manager/**'
      # check if one of the used packages is changed
      - 'packages/types/**'
      - 'packages/config/**'
      - 'packages/utils/**'

jobs:
  check_node_manager_app:
    name: Check Node Manager App
    uses: Aventus-Network-Services/shared-workflows/.github/workflows/check-yarn-application.yml@v5.12.0
    with:
      working_directory: apps/node-manager
      build_command: |
        yarn workspace @avn/types run build
        yarn workspace @avn/config run build
        yarn workspace @avn/utils run build
