name: Check Metadata package

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/metadata/**'

jobs:
  check_search_app:
    name: Check Tokens App
    uses: Aventus-Network-Services/shared-workflows/.github/workflows/check-yarn-application.yml@v5.12.0
    with:
      working_directory: packages/metadata
      build_command: |
        yarn workspace @avn/types run build
        yarn workspace @avn/config run build
