name: Check Tokens app

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, edited]
    branches: [main]
    paths:
      - 'apps/tokens/**'
      # check if one of the used packages is changed
      - 'packages/types/**'
      - 'packages/config/**'
      - 'packages/utils/**'

jobs:
  check_search_app:
    name: Check Tokens App
    uses: AventusDAO/shared-workflows/.github/workflows/check-yarn-application.yml@v5.20.0
    with:
      checkout_repository: ${{github.event.pull_request.head.repo.full_name}}
      checkout_ref: ${{github.event.pull_request.head.ref}}
      working_directory: apps/tokens
      build_command: |
        yarn workspace @avn/types run build
        yarn workspace @avn/config run build
        yarn workspace @avn/utils run build
