name: Check Balances app

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/balances/**'
      # check if one of the used packages is changed
      - 'packages/types/**'
      - 'packages/config/**'
      - 'packages/utils/**'

defaults:
  run:
    working-directory: apps/balances

jobs:
  check_balances_app:
    name: Check Balances App
    uses: Aventus-Network-Services/shared-workflows/.github/workflows/check-yarn-application.yml@v5.11.0
    with:
    build_command: |
      yarn workspace @avn/types run build
      yarn workspace @avn/config run build
      yarn workspace @avn/utils run build
