name: Check Staking app

on:
  pull_request_target:
    branches: [main]
    paths:
      - 'apps/staking/**'
      # check if one of the used packages is changed
      - 'packages/types/**'
      - 'packages/config/**'
      - 'packages/utils/**'

jobs:
  check_search_app:
    name: Check Staking App
    uses: AventusDAO/shared-workflows/.github/workflows/check-yarn-application.yml@v5.12.0
    with:
      working_directory: apps/staking
      build_command: |
        yarn workspace @avn/types run build
        yarn workspace @avn/config run build
        yarn workspace @avn/utils run build
