name: Check Staking app

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/staking/**'
      # check if one of the used packages is changed
      - 'packages/types/**'
      - 'packages/config/**'
      - 'packages/utils/**'

defaults:
  run:
    working-directory: apps/staking

jobs:
  check_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build types package
        run: yarn workspaces @avn/types run build
      - name: Build utils package
        run: yarn workspaces @avn/config run build
      - name: Build utils package
        run: yarn workspaces @avn/utils run build
      - name: Run typescript checks
        run: yarn types:check
