name: Check Types package

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/types/**'

defaults:
  run:
    working-directory: packages/types

jobs:
  check_types_package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.6'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Run Typescript checks
        run: yarn types:check
