name: Check Metadata package

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, edited]
    branches: [main]
    paths:
      - 'packages/metadata/**'

jobs:
  check:
    name: Check Tokens App
    uses: AventusDAO/shared-workflows/.github/workflows/check-yarn-application.yml@v5.20.0
    with:
      checkout_repository: ${{github.event.pull_request.head.repo.full_name}}
      checkout_ref: ${{github.event.pull_request.head.ref}}
      working_directory: packages/metadata
      build_command: |
        yarn workspace @avn/types run build
        yarn workspace @avn/config run build
