name: Docker Build

on:
  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: ubuntu-latest
      short_image_name:
        required: true
        type: string
      ecr_repository_prefix:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      config_creds:
        required: false
        type: boolean
        default: true
    secrets:
      aws_access_key:
        required: false
      aws_secret_key:
        required: false

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    name: Build docker
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        if: ${{ inputs.config_creds }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key }}
          aws-secret-access-key: ${{ secrets.aws_secret_key }}
          aws-region: ${{ inputs.aws_region }}

      - name: Configure AWS credentials Role
        if: ${{ !inputs.config_creds }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.aws_region }}

      - name: AWS ECR login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ inputs.aws_account_id }}

      - name: Create tag for PR
        if: github.ref != 'refs/heads/main'
        run: echo "DOCKER_TAG=${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository_prefix }}/${{ inputs.short_image_name }}:pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Create tag for merge
        if: github.ref == 'refs/heads/main'
        run: echo "DOCKER_TAG=${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository_prefix }}/${{ inputs.short_image_name }}:${GITHUB_SHA::7},${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository_prefix }}/${{ inputs.short_image_name }}:latest" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ env.DOCKER_TAG }}