name: Check linter and prettier

on:
  pull_request:
    branches: [main]

jobs:
  check_linter_prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.6'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Run lint checks
        run: yarn lint:check
      # Disabled temporarily until the Prettier is fixed in the next PR
      # - name: Run pretty checks
      #   run: yarn prettier:check
