name: Check linter and prettier for all apps and packages

on:
  pull_request:
    branches: [main]

jobs:
  check_linter_prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Run lint checks
        run: yarn lint:check
      - name: Run pretty checks
        run: yarn prettier:check
