name: Staking Types

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/staking/**'

defaults:
  run:
    working-directory: apps/staking

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Run typescript checks
        run: yarn types:check
