name: Check Utils package code

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/utils/**'

defaults:
  run:
    working-directory: packages/utils

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Run Typescript checks
        run: yarn types:check
      - name: Run Eslint checks
        run: yarn eslint:check
